### ISSUE TITLE
Does it support mac os?

### ISSUE THREAD

**Issue by QiBaobin** [iostreamer-X/FuncShell#2]
I got 'exec format error' when running it, I am on a mac, did I miss anything or it's not ready for mac yet? Thanks.

**Comment by iostreamer-X** [comment]
I don't have a mac to test this on, hence I am not sure what the problem is. So, I can safely say that it is not ready for mac yet. I invite you and others to add the support if you want to as I do not have access to any macs

**Comment by QiBaobin** [comment]
I built from source and get a working binary.

stack init
stack build
